version: '3.4'
services:
    configuration-server:
        image:
        restart: always
        container_name: configuration-server
        ports:
            -'8888:8888'
        networks:
            - 'docker-networks'
        
networks: 
    docker-networks: