server:
  port: 8080
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patients
          uri: lb://patients
          order: 8080
          predicates:
            - Path=/patients
        - id: patientHistory
          uri: lb://patienthistory
          order: 8080
          predicates:
            - Path=/patienthistory
            
      loadbalancer:
        ribbon:
          enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8091/auth/realms/futurs
        registration:
          spring-cloud:
            gateway-client:
              client-id: springboot-microservice
              client-secret: cc224963-ec02-486b-83d7-8044b0527cc1
              provider: keycloak
              authorization-grant-type: autorhization_code
              redicrect-url: http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

