server:
  port: 8080
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patients
          uri: lb://patients
          order: 8080
          predicates:
            - Path=/patients
        - id: patientHistory
          uri: lb://patienthistory
          order: 8080
          predicates:
            - Path=/patienthistory
            
      loadbalancer:
        ribbon:
          enabled: false

keycloak:
  realm: Futurs
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: springboot-microservice
  credenctials:
    secret: cc224963-ec02-486b-83d7-8044b0527cc1
  user-resource-role-mappings: true
  bearer-only: true



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

