server:
  port: 8080
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patients
          uri: lb://patients
          order: 8080
          predicates:
            - Path=/patients
        - id: patientHistory
          uri: lb://patienthistory
          order: 8080
          predicates:
            - Path=/patienthistory
            
      loadbalancer:
        ribbon:
          enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true