server:
  port: 8080
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: microservice
          uri: lb://microservice
          order: 8080
          predicates:
            - Path=/microservice
      loadbalancer:
        ribbon:
          enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.86.240:8761/eureka/
  instance:
    preferIpAddress: true