server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost/microservice
    username: user
    password: pass
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MysqL5InnoDBDialect    
    hibernate:
      ddl-auto: enable
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
  h2:
    console:
      enabled: true
      path: /h2-console



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

