spring:
  application:
    name: configuration_server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
       # username:
       # password:

server:
  port: 8888