version: '3.4'
services:

    portainer:
        image: portainer/portainer
        container_name: portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainerdata:/data 
        ports:
            - 9000:9000

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        restart: unless-stopped
        environment: 
            ZOOKEEPER_CLIENT_PORT: 2181
            TZ: ${TZ-EUROPE/Madrid}
    
    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        restart: unless-stopped
        depends_on:
          - zookeeper
        ports:
          - "29092:29092"
        environment:
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
          KAFKA_DELETE_TOPIC_ENABLE: "true"
          TZ: "${TZ-Europe/Madrid}"
    kafka-ui:
        image: provectuslabs/kafka-ui
        container_name: kafka-ui
        ports:
            - "8090:8080"
        restart: always
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
            - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

    configuration-server:
        image: configuration_server:0.0.1-SNAPSHOT
        restart: always
        container_name: configuration-server
        ports:
            - '8888:8888'
        networks:
            - 'docker-networks'


    eureka-server:
        image: eureka_server:0.0.1-SNAPSHOT
        restart: always
        container_name: eureka-server
        ports:
            - '8761:8761'
        networks:
            - 'docker-networks'
    
  
   
    mysql:
        image: mysql:5.7.32
        container_name: mysql
        ports:
            - '3306:3306'
        environment: 
            - MYSQL_DATABASE=microservice
            - MYSQL_USER=user  
            - MYSQL_PASSWORD=password   
            - MYSQL_ROOT_PASSWORD=root  
        networks: 
            - 'docker-networks'
        volumes:
            - ../db:/var/lib/mysql
            - ./bd/:/opt/bd
                    

volumes:
    portainerdata:
        
networks: 
    docker-networks: